Algoritmo "Extras 4 - Exercício 7"
// Curso: Mudança de Rota - Programaando
// Descrição: Esse programa lê um número e informa se ele é divisível por 3 ou não.
// Autor(a): Amanda Del Grecco Santana Simões
// Data atual: 22/12/2021
Var
   VN: Real
   DT: Logico

Inicio
      Escreval ("Por gentileza, informe o valor de um número: ")
      Leia (VN)
      DT <- (VN mod 3 = 0)
      Escreval ("O número é divisível por três? ", DT)

Fimalgoritmo