Algoritmo "Exercicio 1 - Dias da Semana"
// Curso: Mudança de Rota - Programaando
// Descrição: Esse programa mostra todos os dias da semana para um usuário.
// Autor(a): Amanda Del Grecco Santana Simões
// Data atual: 21/12/2021

Var

Inicio
   Escreval ("Os dias da semana são:")
   Escreval ("Segunda-feira")
   Escreval ("Terça-feira")
   Escreval ("Quarta-feira")
   Escreval ("Quinta-feira")
   Escreval ("Sexta-feira")
   Escreval ("Sábado")
   Escreva ("Domingo")

Fimalgoritmo