Algoritmo "Atividade 1"
// Curso   : Mudança de Rota - Programaando
// Descrição   : Esse programa lê o nome de uma pessoa e mostra uma mensagem de boas-vindas para ela.
// Autor(a)    : Amanda Del Grecco Santana Simões
// Data atual  : 18/12/2021
Var
   Nome: Caractere

Inicio
       Escreval ("Qual é o seu nome? ")
       Leia (Nome)
       Escreva ("Olá ", Nome, ", é um prazer te conhecer!")

Fimalgoritmo