Algoritmo "Atividade 6"
// Curso: Mudança de Rota - Programaando
// Descrição: Esse programa lê um número real, informado pelo usuário, e mostra o seu dobro e a sua terça parte.
// Autor(a): Amanda Del Grecco Santana Simões
// Data atual: 18/12/2021
Var
   N, I, TP: Real

Inicio
       Escreval ("Digite um número: ")
       Leia (N)
       I <- (N * 2)
       TP <- (N / 3)
       Escreval ("O dobro de", N, " é", I)
       Escreva ("A terça parte de", N, " é", TP)

Fimalgoritmo