Algoritmo "Atividade 5"
// Curso: Mudança de Rota - Programaando
// Descrição: Esse programa lê um número inteiro, informado pelo usuário, e mostra o seu antecessor e seu sucessor.
// Autor(a): Amanda Del Grecco Santana Simões
// Data atual: 18/12/2021
Var
   N, A, S: Inteiro

Inicio
       Escreval ("Digite um número: ")
       Leia (N)
       A <- (N - 1)
       S <- (N + 1)
       Escreval ("O antecessor de: ", N, " é", A)
       Escreva ("O sucessor de: ", N, " é", S)

Fimalgoritmo