Algoritmo "Atividade 8"
// Curso: Mudança de Rota - Programaando
// Descrição: Esse programa lê quanto dinheiro uma pessoa tem na carteira (em R$) e mostre quantos dólares ela pode comprar.
// Autor(a): Amanda Del Grecco Santana Simões
// Data atual: 19/12/2021
Var
   R, D: Real

Inicio
       Escreval ("Digite o valor em Real: ")
       Leia (R)
       D <- (R / 3.45)
       Escreva ("Com ", R, " reais você pode comprar: ", D, " dólar(es)")

Fimalgoritmo